<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNp4n5zz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNp4n5zz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNp4n5zz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNp4n5zz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNp4n5zz\appProdProjectContainer([
    'container.build_hash' => 'Np4n5zz',
    'container.build_id' => '0f763e97',
    'container.build_time' => 1638783481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNp4n5zz');
